### ISSUE TITLE
Validation is not generated for arrays and their items

### ISSUE THREAD

**Issue by rdner** [contiamo/openapi-generator-go#26]
For example,

```yaml
    ResolveEntitiesRequest:
      type: object
      required:
        - ids
      properties:
        ids:
          type: array
          description: UUIDs of the entities to resolve. Maximum size is the maximum supported size by the database in a single query. https://stackoverflow.com/questions/1009706/postgresql-max-number-of-parameters-in-in-clause
          minItems: 1
          maxItems: 32767
          items:
            type: string
            format: uuid
```

is producing

```go
// This file is auto-generated, DO NOT EDIT.
//
// Source:
//     Title: Contiamo Authentication Service
//     Version: 2.0
package models

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// ResolveEntitiesRequest is an object.
type ResolveEntitiesRequest struct {
	// Ids: UUIDs of the entities to resolve. Maximum size is the maximum supported size by the database in a single query. https://stackoverflow.com/questions/1009706/postgresql-max-number-of-parameters-in-in-clause
	Ids []string `json:"ids"`
}

// Validate implements basic validation for this model
func (m ResolveEntitiesRequest) Validate() error {
	return validation.Errors{
		"ids": validation.Validate(
			m.Ids, validation.Required,
		),
	}.Filter()
}

// GetIds returns the Ids property
func (m ResolveEntitiesRequest) GetIds() []string {
	return m.Ids
}

// SetIds sets the Ids property
func (m ResolveEntitiesRequest) SetIds(val []string) {
	m.Ids = val
}
```

So, there are some validation rules missing:

* There is no validation if each item of the array is a valid format (UUID in this case)
* There is no validation for the array sizing (min, max length)
