### ISSUE TITLE
Add validation for value types

### ISSUE THREAD

**Issue by rdner** [contiamo/openapi-generator-go#30]
For example, if I define an integer schema:

```yaml
components:
  schemas:
    Sub1:
      type: integer
      minimum: 5
      maximum: 10
```

it should yield a validation rule in the generated type.
