### ISSUE TITLE
Mandatory fields cannot fire error on validation

### ISSUE THREAD

**Issue by shinnokdisengir** [contiamo/openapi-generator-go#77]
Hi guys, 
I'm trying to raise errors when I send a request **without some fields** to the server, but unfortunately validation seems works only for values/array fields that haven't ref, so if I omit a struct field that cannot be catch, because become {} during decode (...?).

```bash
curl -X POST localhost:3333/install -d '{"dns": [], "ntp": [], "nodes": []}'
{"response": 3}
```

```yaml
type: object
additionalProperties: false
required:
    - domainName
    - networkMask
    - gateway
    - dns
    - ntp
    - nodes
    - region
    - s3
    - cmc
    - test
properties:
    domainName:
        $ref: "./DomainName.yaml"
    networkMask:
        $ref: "./NetworkMask.yaml"
    gateway:
        $ref: "./IpAddress.yaml"
    dns:
        type: array
        minItems: 1
        maxItems: 2
        items:
            $ref: "./IpAddress.yaml"
    ntp:
        type: array
        minItems: 1
        maxItems: 100
        items:
            $ref: "./Uri.yaml"
    nodes:
        type: array
        minItems: 1
        maxItems: 100
        items:
            $ref: "./Node.yaml"
    region:
        $ref: "./Region.yaml"
    s3:
        $ref: "./S3.yaml"
    cmc:
        $ref: "./Cmc.yaml"
    test:
        type: object
        additionalProperties: false
        properties:
            endPoint:
                $ref: "./DomainName.yaml"
        xml:
            name: cmc

xml:
    name: installRequest
```

```go
err := json.NewDecoder(r.Body).Decode(&installRequest)
log.Default().Println(installRequest)
if err != nil {
	w.WriteHeader(http.StatusBadRequest)
	w.Write([]byte(err.Error()))
	return
}
err = installRequest.Validate()
```

Please tell me if I've been working well to validate data, otherwise which could be the best *new* implementation of `Validate` and how I can procede (for example with middlewares, etc..). Thanks
