### ISSUE TITLE
Missind import time package for format: 'date-time'

### ISSUE THREAD

**Issue by komex** [contiamo/openapi-generator-go#83]
When adding `format: 'date-time'`, go type correctly changes to `time.Time`, but without importing `time` package.

In:
```yaml
    Date:
      title: 'Date'
      type: string
      format: 'date-time'
```

Out:
```go
// This file is auto-generated, DO NOT EDIT.
//
// Source:
//     Title: API Gateway
//     Version: 3.1.1
package model

// Date is a value type. Pointer to the date
type Date time.Time
```
